services:
  database:
    image: postgres-db
    container_name: ${PGHOST}
    build: 
      context: ./db
      dockerfile: ./Dockerfile

    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=${PGDATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${PGPORT} -U ${PGUSER} -d ${PGDATABASE}"]
      start_period: 0s
      interval: 5s
      timeout: 5s
      retries: 5
    

  server:
    image: secrets
    container_name: server
    env_file: .env
    ports:
      - ${PUBLIC_PORT}:${PORT}
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy

volumes:
  postgres-data:
    name: "postgres-data"